site_name: GWASTutorial
site_author: HE Yunye
repo_name: 'GitHub'
repo_url: https://github.com/Cloufield/GWASTutorial
edit_uri: ""
copyright: "GWASTutorial is licensed under the MIT license"
theme:
  name: material
  features:
    - navigation.tabs
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    primary: blue
    accent: blue
    
nav:
    - Home: 
      - "Tutorial guide" : index.md
      - "About" : 99_About.md
    - "Command Line" : 
       - "Linux Basics" : 02_Linux_basics.md
       - "Windows Linux Subsystem" : 82_windows_linux_subsystem.md
       - "Git and github" : 83_git_and_github.md
       - "SSH" : 84_ssh.md
       - "Job scheduler" : 85_job_scheduler.md  
       - "Text editing - awk" : 60_awk.md
       - "Text editing - sed" : 61_sed.md
       - "Resources" : 69_resources.md
    - "Pre-GWAS" :
       - "Sample Dataset" : 01_Dataset.md
       - "Data Formats" : 03_Data_formats.md
       - "Data QC" : 04_Data_QC.md
       - "PCA" : 05_PCA.md
       - "Plot PCA" : plot_PCA.ipynb
    - "GWAS" : 
       - "Association tests - PLINK": 06_Association_tests.md
       - "Visualization": Visualization.ipynb
       - "Whole genome regression - REGENIE" : 32_whole_genome_regression.md
    - "Post-GWAS" :
       - "Annotation" : 07_Annotation.md
       - "Heritability" : 13_heritability.md
       - "LDSC" : 08_LDSC.md
       - "Gene/Gene-set tests" : 09_Gene_based_analysis.md
       - "PRS" : 10_PRS.md
    - Others :
       - "Recommended reading" : 90_Recommended_Reading.md
       - "Anaconda" : 80_anaconda.md
       - "Jupyter notebook" : 81_jupyter_notebook.md

markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocs-jupyter
